### ISSUE TITLE
福岡県那珂川市

### ISSUE THREAD

**Issue by kentaro110u** [code4fukui/localgovjp#3]
2018年10月1日に単独市政に移行したため、JSON/CSV記載の名称の変更が必要だと思います。

**Comment by taisukef** [comment]
ありがとうございます！
アップデートしました

**Comment by kentaro110u** [comment]
度々申し訳ありませんが、自治体コードは`40231`になると思います。
[https://www.pref.fukuoka.lg.jp/uploaded/attachment/59124.pdf](https://www.pref.fukuoka.lg.jp/uploaded/attachment/59124.pdf)

**Comment by taisukef** [comment]
失礼しました！
ありがとうございます
そちらも修正しました
