### ISSUE TITLE
三重県北牟婁郡紀北町役場の位置情報誤り

### ISSUE THREAD

**Issue by kentaro110u** [code4fukui/localgovjp#4]
誤：34.10916667, 136.2313889（紀北町役場 海山総合支所）
正：34.211458, 136.337337（紀北町役場）

上記の通り誤りを発見しました。
修正頂けますと幸いです。

**Comment by taisukef** [comment]
ありがとうございます
確認し、修正しました

https://github.com/code4fukui/localgovjp/commit/28b2806e1fed02d454e40576713a8a043aa4a772
