### ISSUE TITLE
役所・役場の位置情報誤りについて

### ISSUE THREAD

**Issue by kentaro110u** [code4fukui/localgovjp#6]
以下の通り、多数誤りがありますのでご確認ください。

「自治体コード:都道府県・自治体名（正しい緯度, 経度）」の形式で記載します。

01343:北海道鹿部町（42.026639, 140.831672）
01402:北海道岩内町（42.979761, 140.514773）
01638:北海道中札内村（42.697864, 143.134395）
01663:北海道浜中町（43.076292, 145.130953）
02205:青森県五所川原市（40.807835, 140.446118）
02321:青森県鰺ヶ沢町（40.783011, 140.233912）
02387:青森県中泊町（40.960427, 140.434122）
02423:青森県大間町（41.522388, 140.90483）
02445:青森県南部町（40.420343, 141.330307）
03202:岩手県宮古市（39.639554, 141.946115）
03208:岩手県遠野市（39.331014, 141.532352）
03210:岩手県陸前高田市（39.020413, 141.633321）
03214:岩手県八幡平市（39.956511, 141.07112）
03321:岩手県紫波町（39.554536, 141.155796）
03461:岩手県大槌町（39.358196, 141.899731）
04361:宮城県亘理町（38.044263, 140.867924）
04401:宮城県松島町（38.380149, 141.067291）
04581:宮城県女川町（38.445388, 141.442693）
04606:宮城県南三陸町（38.680666, 141.462492）
05203:秋田県横手市（39.313777, 140.566636）
05211:秋田県潟上市（39.857288, 140.013049）
05303:秋田県小坂町（40.332926, 140.736191）
06209:山形県長井市（38.106088, 140.033947）
06382:山形県川西町（38.005203, 140.053181）
06461:山形県遊佐町（39.014836, 139.908662）
07211:福島県田村市（37.440621, 140.57631）
07301:福島県桑折町（37.85472, 140.520851）
07405:福島県西会津町（37.587396, 139.649301）
07447:福島県会津美里町（37.464985, 139.834177）
07464:福島県泉崎村（37.153784, 140.303363）
07501:福島県石川町（37.157072, 140.446775）
07503:福島県平田村（37.221995, 140.575655）
07545:福島県大熊町（37.382087, 140.958264）
07546:福島県双葉町（36.921861, 140.800626）
08203:茨城県土浦市（36.078391, 140.204143）
08207:茨城県結城市（36.289625, 139.87147）
08227:茨城県筑西市（36.305263, 139.979417）
08229:茨城県稲敷市（35.972927, 140.303583）
09203:栃木県栃木市（36.382414, 139.734111）
09216:栃木県下野市（36.395227, 139.85192）
09411:栃木県那珂川町（36.736223, 140.17282）
10206:群馬県沼田市（36.64396, 139.042784）
10344:群馬県榛東村（36.438647, 138.967118）
10424:群馬県長野原町（36.544321, 138.649837）
10429:群馬県東吾妻町（36.571564, 138.820571）
10521:群馬県板倉町（36.225962, 139.601938）
11203:埼玉県川口市（35.806733, 139.7234）
11243:埼玉県吉川市（35.895962, 139.855651）
11346:埼玉県川島町（35.992494, 139.484352）
12206:千葉県木更津市（35.381208, 139.924905）
12215:千葉県旭市（35.716116, 140.648217）
13116:東京都豊島区（35.726121, 139.716678）
13209:東京都町田市（35.546559, 139.438527）
13401:東京都八丈町（33.112802, 139.789065）
14100:神奈川県横浜市（35.450195, 139.634903）
15202:新潟県長岡市（37.446587, 138.851224）
15205:新潟県柏崎市（37.364903, 138.557756）
15206:新潟県新発田市（37.947954, 139.327151）
15213:新潟県燕市（37.673149, 138.882249）
15225:新潟県魚沼市（37.236431, 138.963775）
16205:富山県氷見市（36.855978, 136.972868）
16207:富山県黒部市（36.87151, 137.448028）
16210:富山県南砺市（36.557453, 136.875434）
16211:富山県射水市（36.730479, 137.075399）
17211:石川県能美市（36.446888, 136.554028）
17463:石川県能登町（37.310414, 137.147782）
18481:福井県高浜町（35.487904, 135.545969）
20218:長野県千曲市（36.530707, 138.114895）
20220:長野県安曇野市（36.303933, 137.905755）
20323:長野県御代田町（36.322732, 138.506505）
20350:長野県長和町（36.269903, 138.258071）
20410:長野県根羽村（35.255296, 137.581784）
20422:長野県上松町（35.782187, 137.693235）
20451:長野県朝日村（36.129115, 137.867267）
20452:長野県筑北村（36.402654, 138.011775）
21201:岐阜県岐阜市（35.426201, 136.759937）
21361:岐阜県垂井町（35.366268, 136.537944）
21421:岐阜県北方町（35.435721, 136.684408）
23219:愛知県小牧市（35.290311, 136.910948）
23561:愛知県設楽町（35.097298, 137.571225）
24214:三重県いなべ市（35.158426, 136.516697）
24216:三重県伊賀市（34.749886, 136.142286）
25203:滋賀県長浜市（35.380758, 136.278384）
25214:滋賀県米原市（35.315046, 136.291402）
26344:京都府宇治田原町（34.845154, 135.868238）
26407:京都府京丹波町（35.169997, 135.419305）
27209:大阪府守口市（34.735811, 135.561724）
28213:兵庫県西脇市（34.98343, 134.97973）
28218:兵庫県小野市（34.857867, 134.939799）
28224:兵庫県南あわじ市（34.294417, 134.779952）
28464:兵庫県太子町（34.833246, 134.572319）
29207:奈良県五條市（34.356358, 135.695556）
30202:和歌山県海南市（34.157533, 135.239675）
30361:和歌山県湯浅町（34.029418, 135.190427）
30390:和歌山県印南町（33.819533, 135.222515）
30428:和歌山県串本町（33.485686, 135.787016）
31201:鳥取県鳥取市（35.494376, 134.222133）
31403:鳥取県江府町（35.27599, 133.478963）
32207:島根県江津市（35.011621, 132.217754）
32209:島根県雲南市（35.307718, 132.900345）
32441:島根県川本町（34.995211, 132.495853）
32501:島根県津和野町（34.541961, 131.83508）
32526:島根県西ノ島町（36.091825, 133.013467）
32528:島根県隠岐の島町（36.213394, 133.311818）
34545:広島県神石高原町（34.703612, 133.251651）
36206:徳島県阿波市（34.102138, 134.297456）
37322:香川県土庄町（34.486653, 134.188629）
37324:香川県小豆島町（34.479714, 134.30888）
39344:高知県大豊町（33.768594, 133.642959）
39387:高知県仁淀川町（33.575286, 133.171）
39401:高知県中土佐町（33.329273, 133.224785）
39412:高知県四万十町（33.211606, 133.137037）
39428:高知県黒潮町（33.024965, 133.004158）
40217:福岡県筑紫野市（33.487386, 130.526007）
40227:福岡県嘉麻市（33.598421, 130.719217）
40401:福岡県小竹町（33.696782, 130.707784）
40608:福岡県大任町（33.612164, 130.853742）
41206:佐賀県武雄市（33.194873, 130.021557）
41208:佐賀県小城市（33.273776, 130.21728）
41210:佐賀県神埼市（33.311423, 130.371662）
43203:熊本県人吉市（32.216889, 130.739392）
43206:熊本県玉名市（32.935266, 130.562877）
43433:熊本県南阿蘇村（32.845046, 131.017881）
43443:熊本県益城町（32.800608, 130.817015）
44209:大分県豊後高田市（33.556202, 131.446931）
44214:大分県国東市（33.563327, 131.732264）
45421:宮崎県門川町（32.470914, 131.646471）
45442:宮崎県日之影町（32.659465, 131.380909）
46221:鹿児島県志布志市（31.477502, 131.099836）
46505:鹿児島県屋久島町（30.389893, 130.651119）
46531:鹿児島県天城町（27.81166, 128.897749）
46535:鹿児島県与論町（27.044904, 128.421675）
47201:沖縄県那覇市（26.212295, 127.679218）
47207:沖縄県石垣市（24.344419, 124.185246）
47212:沖縄県豊見城市（26.177136, 127.681225）
47214:沖縄県宮古島市（24.789971, 125.294752）
47215:沖縄県南城市（26.16319, 127.770625）
47328:沖縄県中城村（26.26201, 127.789618）
47329:沖縄県西原町（26.222856, 127.758819）
47362:沖縄県八重瀬町（26.15834, 127.718649）

**Comment by taisukef** [comment]
ありがとうございます！いただいた情報に変更しました
https://github.com/code4fukui/localgovjp/commit/6f95f3582d8cf8bcb7b903a020dc672fa920dba1
